# Generated by Django 5.0 on 2024-02-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('UserLevel', models.TextField(choices=[('Administrator', 'Administrator'), ('Student', 'Student'), ('Lecturer', 'Lecturer')], max_length=30)),
                ('Password', models.CharField(max_length=12)),
                ('PhoneNo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('PlateNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('VehicleType', models.TextField(max_length=30)),
                ('Status', models.TextField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=50)),
                ('LastMaintenance', models.DateField(blank=True, null=True)),
                ('NextMaintenance', models.DateField(blank=True, null=True)),
                ('PlateNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.users')),
                ('PlateNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.vehicle')),
            ],
        ),
    ]
