# Generated by Django 5.0 on 2024-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_profile_alter_booking_userid_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleType',
            field=models.TextField(choices=[('Van', 'Van'), ('Car', 'Car'), ('Bus', 'Bus')], default='Van', max_length=30),
        ),
    ]
