# Generated by Django 5.0 on 2024-02-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_profile_userlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='VehicleType',
            field=models.TextField(choices=[('Van', 'Van'), ('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Bus', 'Bus')], default='Van', max_length=30),
        ),
    ]
